### ISSUE TITLE
[BE/FIX] DB 수정 사항 Migration

### ISSUE THREAD

**Issue by Hyyena** [woocheonjae/HiRolling-Server#21]
# Migration 에러

### ✅(해결) sequelize-cli를 이용해 마이그레이션 작업 중 설정 파일을 불러오지 못하는 에러 발생

```bash
❯ sequelize db:migrate

Sequelize CLI [Node: 18.12.1, CLI: 3.2.0c, ORM: 6.28.0]

Loaded configuration file "dist/src/config/config.js".

ERROR: Dialect needs to be explicitly supplied as of v4.0.0
```

- 설정 파일에서 `.env` 파일을 읽지 못해 에러 발생
- `json` 파일에 설정을 직접 적어서 해결

### migration이 수행되지 않는 에러 발생

```bash
❯ node_modules/.bin/sequelize db:migrate:undo:all && node_modules/.bin/sequelize db:migrate

Sequelize CLI [Node: 18.12.1, CLI: 3.2.0c, ORM: 6.28.0]

Loaded configuration file "src/config/migrationConfig.json".
Using environment "development".
No executed migrations found.

Sequelize CLI [Node: 18.12.1, CLI: 3.2.0c, ORM: 6.28.0]

Loaded configuration file "src/config/migrationConfig.json".
Using environment "development".
No migrations were executed, database schema was already up to date.
```

- [스택오버플로우](https://stackoverflow.com/questions/39621568/my-models-for-db-using-sequelize-dont-doing-migration)를 참고하여 migration 정보를 저장하는 `SequelizeMeta` 테이블이 생성됐는지 확인 후 이를 지우고 실행해 본 결과 동일한 에러 발생

**Comment by j2woo** [comment]
## 1. ./models/personalPostAttachedImage에서 속성명 수정
-  group_post_image-> personal_post_image 수정

## 2. ./models/personalPost 속성 수정
- anonymous_type: @AllowNull(false)-> @AllowNull(true) 수정
